version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  data_ingestor:
    build:
      context: .
      dockerfile: ./data_ingestor/Dockerfile
    restart: always
    depends_on:
      - redis

  wallet_watcher:
    build:
      context: .
      dockerfile: ./wallet_watcher/Dockerfile
    restart: always
    depends_on:
      - redis

  signal_engine:
    build:
      context: .
      dockerfile: ./signal_engine/Dockerfile
    restart: always
    depends_on:
      - redis

  execution_engine:
    build:
      context: .
      dockerfile: ./execution_engine/Dockerfile
    restart: always
    depends_on:
      - redis

  telegram_control:
    build:
      context: .
      dockerfile: ./telegram_control/Dockerfile
    restart: always
    depends_on:
      - redis
